apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-first-container 
    image: nginx
    ports:
      - name: http
        protocol: TCP
        containerPort: 80
    - name: my-second-container
      image: nginx
      ports:
       - name: http
         protocol: TCP
         containerPort: 8080
         

         
        
        
